### ISSUE TITLE
Library Details

### ISSUE THREAD

**Issue by castasint** [brianmanderson/PDF_To_JPG_CSharp#1]
Hi @brianmanderson  

I see that you've used the syncfusion library to convert the pdf to jpg. Is it open source and can be used for production apps?
 Please advise.

**Comment by brianmanderson** [comment]
Hi @castasint,

The library is open source, just use NuGet in Visual Studio. I can't speak towards allowance within production applications, this is an open source project. Please make no assumptions ^^

Sorry I can't be more helpful
Brian
